---
- name: "install webapp v3"
  become: yes
  hosts: prod
  tasks:
    - name: Generate html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
      notify: index.html changed

  handlers:
    - name: index.html changed
      service:
        name: nginx
        state: restarted

...
