# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "ansible" do |ansible|
      ansible.vm.box = "geerlingguy/centos7"
      ansible.vm.network "private_network", type: "static", ip: "192.168.99.10"
      ansible.vm.hostname = "ansible"
      ansible.vm.provider "virtualbox" do |v|
        v.name = "ansible"
        v.memory = 2048
        v.cpus = 2
      end
      ansible.vm.provision :shell do |shell|
        shell.path = "install_ansible.sh"
        shell.args = ["amaster", "192.168.99.10"]
      end
    end
    aclients=2
    ram_aclient=2048
    cpu_aclient=2
    (1..aclients).each do |i|
      config.vm.define "aclient#{i}" do |aclient|
        aclient.vm.box = "geerlingguy/centos7"
        aclient.vm.network "private_network", type: "static", ip: "192.168.99.1#{i}"
        aclient.vm.hostname = "aclient#{i}"
        aclient.vm.provider "virtualbox" do |v|
          v.name = "aclient#{i}"
          v.memory = ram_aclient
          v.cpus = cpu_aclient
        end
        aclient.vm.provision :shell do |shell|
          shell.path = "install_ansible.sh"
          shell.args = ["node", "192.168.99.10"]
        end
      end
    end
  end
  